// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AsNoTrackin_UseQueryTrackingBehavior;

#nullable disable

namespace AsNoTrackin_UseQueryTrackingBehavior.Migrations
{
    [DbContext(typeof(ETicaretContext))]
    [Migration("20230717150447_Tracking")]
    partial class Tracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("KitapYazar", b =>
                {
                    b.Property<int>("KitaplarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YazarlarId")
                        .HasColumnType("INTEGER");

                    b.HasKey("KitaplarId", "YazarlarId");

                    b.HasIndex("YazarlarId");

                    b.ToTable("KitapYazar");
                });

            modelBuilder.Entity("KullaniciRol", b =>
                {
                    b.Property<int>("KullanicilarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RollerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("KullanicilarId", "RollerId");

                    b.HasIndex("RollerId");

                    b.ToTable("KullaniciRol");
                });

            modelBuilder.Entity("_11_AsNoTrackin_UseQueryTrackingBehavior_AsNoTrackingWithIdentityResolution.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SayfaSayisi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("_11_AsNoTrackin_UseQueryTrackingBehavior_AsNoTrackingWithIdentityResolution.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("_11_AsNoTrackin_UseQueryTrackingBehavior_AsNoTrackingWithIdentityResolution.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("_11_AsNoTrackin_UseQueryTrackingBehavior_AsNoTrackingWithIdentityResolution.Yazar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("YazarAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Yazarlar");
                });

            modelBuilder.Entity("KitapYazar", b =>
                {
                    b.HasOne("_11_AsNoTrackin_UseQueryTrackingBehavior_AsNoTrackingWithIdentityResolution.Kitap", null)
                        .WithMany()
                        .HasForeignKey("KitaplarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_11_AsNoTrackin_UseQueryTrackingBehavior_AsNoTrackingWithIdentityResolution.Yazar", null)
                        .WithMany()
                        .HasForeignKey("YazarlarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KullaniciRol", b =>
                {
                    b.HasOne("_11_AsNoTrackin_UseQueryTrackingBehavior_AsNoTrackingWithIdentityResolution.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("KullanicilarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_11_AsNoTrackin_UseQueryTrackingBehavior_AsNoTrackingWithIdentityResolution.Rol", null)
                        .WithMany()
                        .HasForeignKey("RollerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
